version: '3'

volumes:
  feelgood-db:

networks:
  feelgood_network:
    name: feelgood_network

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'feelgood'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    networks:
      - feelgood_network
    volumes:
      - feelgood-db:/var/lib/mysql
    expose:
      - '3307'