version: '3.4'

volumes:
  my-db-test:

services:
  localstack-test:
    container_name: localstack-test
    image: localstack/localstack:latest
    ports:
      - '4567:4566'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3, sqs, ses, sns, ecr, lambda
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
    volumes:
      - ./localstack-script.sh:/etc/localstack/init/ready.d/script.sh
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./aws:/etc/localstack/init/ready.d
      - './aws/cors.json:/opt/code/localstack/cors.json'

  mysql-test:
    container_name: mysql-test
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'feelgood'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my-db-test:/var/lib/mysql
